name: MiActyl
logo: /favicon.png
domain: http://localhost:5173/client

database: jdbc:mysql://user:password@localhost:3306/database

website:
  port: 80

discordserver:
  enabled: true
  invitelink: https://discord.gg/RvmdmEfKFX

linkvertise:
  enabled: true
  userid: 0
  coins: 10
linkpays:
  enabled: true
  userid: 0
  coins: 10
  redirectOnStart: false

pterodactyl:
  domain: https://panel.example.com
  key: "pterodactyl_application_api_key_here"
api:
  client:
    bot:
      token: "discord_bot_token_here"
      joinguild:
        enabled: true
        guilds:
          - 0
        registeredrole: "0"
      overresourcessuspend: true # OOM
    renew:
      enabled: true
      time: 1 # time of renew server (in hours)
      cost: 13 # cost of renew server
      maxTimeAlive: 72 # time when server will be deleted if not renewed (in hours)
      deploy: 0 # cost of server deploy
      deployTime: 1 # time of renew server after deploy (in hours)
      deployAdditionalCost: # add additional cost to deploy cost
        ram: 0 # per 1GB
        cpu: 0 # per 100%
        disk: 0 # per 1GB
        databases: 0 # per 1
        backups: 0 # per 1
        ports: 0 # per 1
      addotionalcost: # add additional cost to renew cost
        ram: 0 # per 1GB
        cpu: 0 # per 100%
        disk: 0 # per 1GB
        databases: 0 # per 1
        backups: 0 # per 1
        ports: 0 # per 1

    oauth2:
      id: "discord_application_id_here"
      secret: "discord_application_secret_here"